# Generated by Django 4.2.6 on 2023-10-06 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Szolgatatasok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('megnevezes', models.CharField(max_length=100)),
                ('leiras', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Arak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar', models.CharField(max_length=100)),
                ('szolgaltatas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.szolgatatasok')),
            ],
        ),
    ]
