# Generated by Django 4.2.6 on 2023-11-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_sliderslide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sliderslide',
            old_name='hotel_Main_Img',
            new_name='img',
        ),
    ]
